
#include "../include/macro_preset_names.h"
#include <bits/stdc++.h>

using namespace std;
// String switch paridgam


string macroStrings[][3] = {
    // beh model behParams
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvOneCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvMovingBlueCoin", "MODEL_BLUE_COIN", "0" },
    { "bhvBlueCoinSliding", "MODEL_BLUE_COIN", "0" },  // unused
    { "bhvRedCoin", "MODEL_RED_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvCoinFormation", "MODEL_NONE", "0" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_RING" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_ARROW" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_FLYING" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_FLYING | COIN_FORMATION_FLAG_VERTICAL" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_FLYING | COIN_FORMATION_FLAG_RING" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_FLYING | COIN_FORMATION_FLAG_RING | COIN_FORMATION_FLAG_VERTICAL" },
    { "bhvCoinFormation", "MODEL_NONE", "COIN_FORMATION_FLAG_FLYING | COIN_FORMATION_FLAG_ARROW" }, // unused
    { "bhvHiddenStarTrigger", "MODEL_NONE", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvUnusedFakeStar", "MODEL_STAR", "0" }, // unused
    { "bhvMessagePanel", "MODEL_WOODEN_SIGNPOST", "0" },
    { "bhvCannonClosed", "MODEL_DL_CANNON_LID", "0" },
    { "bhvBobombBuddyOpensCannon", "MODEL_BOBOMB_BUDDY", "0" },
    { "bhvButterfly", "MODEL_BUTTERFLY", "0" }, // unused
    { "bhvBouncingFireball", "MODEL_NONE", "0" }, // unused
    { "bhvLargeFishGroup", "MODEL_NONE", "0" },  // unused
    { "bhvLargeFishGroup", "MODEL_NONE", "1" },
    { "bhvBetaFishSplashSpawner", "MODEL_NONE", "0" },
    { "bhvHidden1upInPoleSpawner", "MODEL_NONE", "0" },
    { "bhvGoomba", "MODEL_GOOMBA", "1" },
    { "bhvGoomba", "MODEL_GOOMBA", "2" },
    { "bhvGoombaTripletSpawner", "MODEL_NONE", "0" },
    { "bhvGoombaTripletSpawner", "MODEL_NONE", "8" },  // unused
    { "bhvSignOnWall", "MODEL_NONE", "0" },
    { "bhvChuckya", "MODEL_CHUCKYA", "0" },
    { "bhvCannon", "MODEL_CANNON_BASE", "0" },
    { "bhvGoomba", "MODEL_GOOMBA", "0" },
    { "bhvHomingAmp", "MODEL_AMP", "0" },
    { "bhvCirclingAmp", "MODEL_AMP", "0" },
    { "bhvCarrySomething1", "MODEL_UNKNOWN_7D", "0" },  // unused
    { "bhvBetaTrampolineTop", "MODEL_TRAMPOLINE", "0" },  // unused
    { "bhvFreeBowlingBall", "MODEL_BOWLING_BALL", "0" },  // unused
    { "bhvSnufit", "MODEL_SNUFIT", "0" },
    { "bhvRecoveryHeart", "MODEL_HEART", "0" },
    { "bhv1upSliding", "MODEL_1UP", "0" },
    { "bhv1Up", "MODEL_1UP", "0" },
    { "bhv1upJumpOnApproach", "MODEL_1UP", "0" },  // unused
    { "bhvHidden1up", "MODEL_1UP", "0" },
    { "bhvHidden1upTrigger", "MODEL_NONE", "0" },
    { "bhv1Up", "MODEL_1UP", "1" },
    { "bhv1Up", "MODEL_1UP", "2" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvBlueCoinSwitch", "MODEL_BLUE_COIN_SWITCH", "0" },
    { "bhvHiddenBlueCoin", "MODEL_BLUE_COIN", "0" },
    { "bhvCapSwitch", "MODEL_CAP_SWITCH", "0" },  // unused
    { "bhvCapSwitch", "MODEL_CAP_SWITCH", "1" },  // unused
    { "bhvCapSwitch", "MODEL_CAP_SWITCH", "2" },  // unused
    { "bhvCapSwitch", "MODEL_CAP_SWITCH", "3" },  // unused
    { "bhvWaterLevelDiamond", "MODEL_BREAKABLE_BOX", "0" },  // unused
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "0" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "1" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "2" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "3" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "4" },  // unused
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "5" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "6" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "7" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "8" },
    { "bhvBreakableBox", "MODEL_BREAKABLE_BOX", "0" },
    { "bhvBreakableBox", "MODEL_BREAKABLE_BOX", "1" },
    { "bhvPushableMetalBox", "MODEL_METAL_BOX", "0" },
    { "bhvBreakableBoxSmall", "MODEL_BREAKABLE_BOX_SMALL", "0" },
    { "bhvFloorSwitchHiddenObjects", "MODEL_PURPLE_SWITCH", "0" },
    { "bhvHiddenObject", "MODEL_BREAKABLE_BOX", "0" },
    { "bhvHiddenObject", "MODEL_BREAKABLE_BOX", "1" },  // unused
    { "bhvHiddenObject", "MODEL_BREAKABLE_BOX", "2" },  // unused
    { "bhvBreakableBox", "MODEL_BREAKABLE_BOX", "3" },
    { "bhvKoopaShellUnderwater", "MODEL_KOOPA_SHELL", "0" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "9" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvBulletBill", "MODEL_BULLET_BILL", "0" },  // unused
    { "bhvHeaveHo", "MODEL_HEAVE_HO", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvThwomp2", "MODEL_THWOMP", "0" },  // unused
    { "bhvFireSpitter", "MODEL_BOWLING_BALL", "0" },
    { "bhvFlyGuy", "MODEL_FLYGUY", "1" },
    { "bhvJumpingBox", "MODEL_BREAKABLE_BOX", "0" },
    { "bhvTripletButterfly", "MODEL_BUTTERFLY", "0" },
    { "bhvTripletButterfly", "MODEL_BUTTERFLY", "4" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvSmallBully", "MODEL_BULLY", "0" },
    { "bhvSmallBully", "MODEL_BULLY_BOSS", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvStub1D0C", "MODEL_UNKNOWN_58", "0" },  // unused
    { "bhvBouncingFireball", "MODEL_NONE", "0" },
    { "bhvFlamethrower", "MODEL_NONE", "4" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvWoodenPost", "MODEL_WOODEN_POST", "0" },
    { "bhvWaterBombSpawner", "MODEL_NONE", "0" },
    { "bhvEnemyLakitu", "MODEL_ENEMY_LAKITU", "0" },
    { "bhvKoopa", "MODEL_KOOPA_WITH_SHELL", "2" },  // unused
    { "bhvKoopaRaceEndpoint", "MODEL_NONE", "0" },  // unused
    { "bhvBobomb", "MODEL_BLACK_BOBOMB", "0" },
    { "bhvWaterBombCannon", "MODEL_CANNON_BASE", "0" },  // unused
    { "bhvBobombBuddyOpensCannon", "MODEL_BOBOMB_BUDDY", "0" },  // unused
    { "bhvWaterBombCannon", "MODEL_CANNON_BASE", "0" },
    { "bhvBobomb", "MODEL_BLACK_BOBOMB", "1" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvUnusedFakeStar", "MODEL_UNKNOWN_54", "0 " },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvUnagi", "MODEL_UNAGI", "0" },  // unused
    { "bhvSushiShark", "MODEL_SUSHI", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvStaticObject", "MODEL_KLEPTO", "0" },  // unused
    { "bhvTweester", "MODEL_TWEESTER", "0" },  // unused
    { "bhvPokey", "MODEL_NONE", "0" },
    { "bhvPokey", "MODEL_NONE", "0" },  // unused
    { "bhvToxBox", "MODEL_SSL_TOX_BOX", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvMontyMole", "MODEL_MONTY_MOLE", "0" },  // unused
    { "bhvMontyMole", "MODEL_MONTY_MOLE", "1" },
    { "bhvMontyMoleHole", "MODEL_DL_MONTY_MOLE_HOLE", "0" },
    { "bhvFlyGuy", "MODEL_FLYGUY", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvWigglerHead", "MODEL_WIGGLER_HEAD", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvSpindrift", "MODEL_SPINDRIFT", "0" },
    { "bhvMrBlizzard", "MODEL_MR_BLIZZARD_HIDDEN", "0" },
    { "bhvMrBlizzard", "MODEL_MR_BLIZZARD_HIDDEN", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvSmallPenguin", "MODEL_PENGUIN", "0" },  // unused
    { "bhvTuxiesMother", "MODEL_PENGUIN", "0" },  // unused
    { "bhvTuxiesMother", "MODEL_PENGUIN", "0" },  // unused
    { "bhvMrBlizzard", "MODEL_MR_BLIZZARD_HIDDEN", "1" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvHauntedChair", "MODEL_HAUNTED_CHAIR", "0" },  // unused
    { "bhvHauntedChair", "MODEL_HAUNTED_CHAIR", "0" },
    { "bhvHauntedChair", "MODEL_HAUNTED_CHAIR", "0" },  // unused
    { "bhvGhostHuntBoo", "MODEL_BOO", "0" },  // unused
    { "bhvGhostHuntBoo", "MODEL_BOO", "0" },  // unused
    { "bhvCourtyardBooTriplet", "MODEL_BOO", "0" },  // unused
    { "bhvBooWithCage", "MODEL_BOO", "0" },  // unused
    { "bhvAlphaBooKey", "MODEL_BETA_BOO_KEY", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvChirpChirp", "MODEL_NONE", "0" },
    { "bhvSeaweedBundle", "MODEL_NONE", "0" },
    { "bhvBetaChestBottom", "MODEL_TREASURE_CHEST_BASE", "0" },  // unused
    { "bhvBowserBomb", "MODEL_WATER_MINE", "0" },  // unused
    { "bhvLargeFishGroup", "MODEL_NONE", "2" },  // unused
    { "bhvLargeFishGroup", "MODEL_NONE", "3" },
    { "bhvJetStreamRingSpawner", "MODEL_WATER_RING", "0" },  // unused
    { "bhvJetStreamRingSpawner", "MODEL_WATER_RING", "0" },  // unused
    { "bhvSkeeter", "MODEL_SKEETER", "0" },
    { "bhvClamShell", "MODEL_CLAM_SHELL", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvMacroUkiki", "MODEL_UKIKI", "0" },  // unused
    { "bhvMacroUkiki", "MODEL_UKIKI", "1" },  // unused
    { "bhvPiranhaPlant", "MODEL_PIRANHA_PLANT", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvSmallWhomp", "MODEL_WHOMP", "0" },
    { "bhvChainChomp", "MODEL_CHAIN_CHOMP", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvKoopa", "MODEL_KOOPA_WITH_SHELL", "1" },
    { "bhvKoopa", "MODEL_KOOPA_WITHOUT_SHELL", "0" },  // unused
    { "bhvWoodenPost", "MODEL_WOODEN_POST", "0" },  // unused
    { "bhvFirePiranhaPlant", "MODEL_PIRANHA_PLANT", "0" },
    { "bhvFirePiranhaPlant", "MODEL_PIRANHA_PLANT", "1" },  // unused
    { "bhvKoopa", "MODEL_KOOPA_WITH_SHELL", "4" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvMoneybagHidden", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvSwoop", "MODEL_SWOOP", "0" },
    { "bhvSwoop", "MODEL_SWOOP", "1" },
    { "bhvMrI", "MODEL_NONE", "0" },
    { "bhvScuttlebugSpawn", "MODEL_NONE", "0" },
    { "bhvScuttlebug", "MODEL_SCUTTLEBUG", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_UNKNOWN_54", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvTTCRotatingSolid", "MODEL_TTC_ROTATING_CUBE", "0" },
    { "bhvTTCRotatingSolid", "MODEL_TTC_ROTATING_PRISM", "1" },
    { "bhvTTCPendulum", "MODEL_TTC_PENDULUM", "0" },
    { "bhvTTCTreadmill", "MODEL_TTC_LARGE_TREADMILL", "0" },
    { "bhvTTCTreadmill", "MODEL_TTC_SMALL_TREADMILL", "1" },
    { "bhvTTCMovingBar", "MODEL_TTC_PUSH_BLOCK", "0" },
    { "bhvTTCCog", "MODEL_TTC_ROTATING_HEXAGON", "0" },
    { "bhvTTCCog", "MODEL_TTC_ROTATING_TRIANGLE", "2" },
    { "bhvTTCPitBlock", "MODEL_TTC_PIT_BLOCK", "0" },
    { "bhvTTCPitBlock", "MODEL_TTC_PIT_BLOCK_UNUSED", "1" },  // unused
    { "bhvTTCElevator", "MODEL_TTC_ELEVATOR_PLATFORM", "0" },
    { "bhvTTC2DRotator", "MODEL_TTC_CLOCK_HAND", "0" },
    { "bhvTTCSpinner", "MODEL_TTC_SPINNER", "0" },
    { "bhvTTC2DRotator", "MODEL_TTC_SMALL_GEAR", "1" },
    { "bhvTTC2DRotator", "MODEL_TTC_LARGE_GEAR", "1" },
    { "bhvTTCTreadmill", "MODEL_TTC_LARGE_TREADMILL", "2" },
    { "bhvTTCTreadmill", "MODEL_TTC_SMALL_TREADMILL", "3" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "10" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "11" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "12" },
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "13" },  // unused
    { "bhvExclamationBox", "MODEL_EXCLAMATION_BOX", "14" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvSlidingPlatform2", "MODEL_BITS_SLIDING_PLATFORM", "0" },  // unused
    { "bhvSlidingPlatform2", "MODEL_BITS_TWIN_SLIDING_PLATFORMS", "0" },  // unused
    { "bhvAnotherTiltingPlatform", "MODEL_BITDW_SLIDING_PLATFORM", "0" },  // unused
    { "bhvOctagonalPlatformRotating", "MODEL_BITS_OCTAGONAL_PLATFORM", "0" },  // unused
    { "bhvAnimatesOnFloorSwitchPress", "MODEL_BITS_STAIRCASE", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvFerrisWheelAxle", "MODEL_BITS_FERRIS_WHEEL_AXLE", "0" },  // unused
    { "bhvActivatedBackAndForthPlatform", "MODEL_BITS_ARROW_PLATFORM", "0" },  // unused
    { "bhvSeesawPlatform", "MODEL_BITS_SEESAW_PLATFORM", "0" },  // unused
    { "bhvSeesawPlatform", "MODEL_BITS_TILTING_W_PLATFORM", "0" },  // unused
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" },
    { "bhvYellowCoin", "MODEL_YELLOW_COIN", "0" }
};

map<string, MacroPresets> macroNameMap = {
    { "macro_yellow_coin" , macro_yellow_coin},
    { "macro_yellow_coin_2" , macro_yellow_coin_2},
    { "macro_moving_blue_coin" , macro_moving_blue_coin},
    { "macro_sliding_blue_coin" , macro_sliding_blue_coin},
    { "macro_red_coin" , macro_red_coin},
    { "macro_empty_5" , macro_empty_5},
    { "macro_coin_line_horizontal" , macro_coin_line_horizontal},
    { "macro_coin_ring_horizontal" , macro_coin_ring_horizontal},
    { "macro_coin_arrow" , macro_coin_arrow},
    { "macro_coin_line_horizontal_flying" , macro_coin_line_horizontal_flying},
    { "macro_coin_line_vertical" , macro_coin_line_vertical},
    { "macro_coin_ring_horizontal_flying" , macro_coin_ring_horizontal_flying},
    { "macro_coin_ring_vertical" , macro_coin_ring_vertical},
    { "macro_coin_arrow_flying" , macro_coin_arrow_flying},
    { "macro_hidden_star_trigger" , macro_hidden_star_trigger},
    { "macro_empty_15" , macro_empty_15},
    { "macro_empty_16" , macro_empty_16},
    { "macro_empty_17" , macro_empty_17},
    { "macro_empty_18" , macro_empty_18},
    { "macro_empty_19" , macro_empty_19},
    { "macro_fake_star" , macro_fake_star},
    { "macro_wooden_signpost" , macro_wooden_signpost},
    { "macro_cannon_closed" , macro_cannon_closed},
    { "macro_bobomb_buddy_opens_cannon" , macro_bobomb_buddy_opens_cannon},
    { "macro_butterfly" , macro_butterfly},
    { "macro_bouncing_fireball_copy" , macro_bouncing_fireball_copy},
    { "macro_fish_group_3" , macro_fish_group_3},
    { "macro_fish_group" , macro_fish_group},
    { "macro_unknown_28" , macro_unknown_28},
    { "macro_hidden_1up_in_pole" , macro_hidden_1up_in_pole},
    { "macro_huge_goomba" , macro_huge_goomba},
    { "macro_tiny_goomba" , macro_tiny_goomba},
    { "macro_goomba_triplet_spawner" , macro_goomba_triplet_spawner},
    { "macro_goomba_quintuplet_spawner" , macro_goomba_quintuplet_spawner},
    { "macro_sign_on_wall" , macro_sign_on_wall},
    { "macro_chuckya" , macro_chuckya},
    { "macro_cannon_open" , macro_cannon_open},
    { "macro_goomba" , macro_goomba},
    { "macro_homing_amp" , macro_homing_amp},
    { "macro_circling_amp" , macro_circling_amp},
    { "macro_unknown_40" , macro_unknown_40},
    { "macro_unknown_41" , macro_unknown_41},
    { "macro_free_bowling_ball" , macro_free_bowling_ball},
    { "macro_snufit" , macro_snufit},
    { "macro_recovery_heart" , macro_recovery_heart},
    { "macro_1up_sliding" , macro_1up_sliding},
    { "macro_1up" , macro_1up},
    { "macro_1up_jump_on_approach" , macro_1up_jump_on_approach},
    { "macro_hidden_1up" , macro_hidden_1up},
    { "macro_hidden_1up_trigger" , macro_hidden_1up_trigger},
    { "macro_1up_2" , macro_1up_2},
    { "macro_1up_3" , macro_1up_3},
    { "macro_empty_52" , macro_empty_52},
    { "macro_blue_coin_switch" , macro_blue_coin_switch},
    { "macro_hidden_blue_coin" , macro_hidden_blue_coin},
    { "macro_wing_cap_switch" , macro_wing_cap_switch},
    { "macro_metal_cap_switch" , macro_metal_cap_switch},
    { "macro_vanish_cap_switch" , macro_vanish_cap_switch},
    { "macro_yellow_cap_switch" , macro_yellow_cap_switch},
    { "macro_unknown_59" , macro_unknown_59},
    { "macro_box_wing_cap" , macro_box_wing_cap},
    { "macro_box_metal_cap" , macro_box_metal_cap},
    { "macro_box_vanish_cap" , macro_box_vanish_cap},
    { "macro_box_koopa_shell" , macro_box_koopa_shell},
    { "macro_box_one_coin" , macro_box_one_coin},
    { "macro_box_three_coins" , macro_box_three_coins},
    { "macro_box_ten_coins" , macro_box_ten_coins},
    { "macro_box_1up" , macro_box_1up},
    { "macro_box_star_1" , macro_box_star_1},
    { "macro_breakable_box_no_coins" , macro_breakable_box_no_coins},
    { "macro_breakable_box_three_coins" , macro_breakable_box_three_coins},
    { "macro_pushable_metal_box" , macro_pushable_metal_box},
    { "macro_breakable_box_small" , macro_breakable_box_small},
    { "macro_floor_switch_hidden_objects" , macro_floor_switch_hidden_objects},
    { "macro_hidden_box" , macro_hidden_box},
    { "macro_hidden_object_2" , macro_hidden_object_2},
    { "macro_hidden_object_3" , macro_hidden_object_3},
    { "macro_breakable_box_giant" , macro_breakable_box_giant},
    { "macro_koopa_shell_underwater" , macro_koopa_shell_underwater},
    { "macro_box_1up_running_away" , macro_box_1up_running_away},
    { "macro_empty_80" , macro_empty_80},
    { "macro_bullet_bill_cannon" , macro_bullet_bill_cannon},
    { "macro_heave_ho" , macro_heave_ho},
    { "macro_empty_83" , macro_empty_83},
    { "macro_thwomp" , macro_thwomp},
    { "macro_fire_spitter" , macro_fire_spitter},
    { "macro_fire_fly_guy" , macro_fire_fly_guy},
    { "macro_jumping_box" , macro_jumping_box},
    { "macro_butterfly_triplet" , macro_butterfly_triplet},
    { "macro_butterfly_triplet_2" , macro_butterfly_triplet_2},
    { "macro_empty_90" , macro_empty_90},
    { "macro_empty_91" , macro_empty_91},
    { "macro_empty_92" , macro_empty_92},
    { "macro_bully" , macro_bully},
    { "macro_bully_2" , macro_bully_2},
    { "macro_empty_95" , macro_empty_95},
    { "macro_unknown_96" , macro_unknown_96},
    { "macro_bouncing_fireball" , macro_bouncing_fireball},
    { "macro_flamethrower" , macro_flamethrower},
    { "macro_empty_99" , macro_empty_99},
    { "macro_empty_100" , macro_empty_100},
    { "macro_empty_101" , macro_empty_101},
    { "macro_empty_102" , macro_empty_102},
    { "macro_empty_103" , macro_empty_103},
    { "macro_empty_104" , macro_empty_104},
    { "macro_empty_105" , macro_empty_105},
    { "macro_wooden_post" , macro_wooden_post},
    { "macro_water_bomb_spawner" , macro_water_bomb_spawner},
    { "macro_enemy_lakitu" , macro_enemy_lakitu},
    { "macro_bob_koopa_the_quick" , macro_bob_koopa_the_quick},
    { "macro_koopa_race_endpoint" , macro_koopa_race_endpoint},
    { "macro_bobomb" , macro_bobomb},
    { "macro_water_bomb_cannon_copy" , macro_water_bomb_cannon_copy},
    { "macro_bobomb_buddy_opens_cannon_copy" , macro_bobomb_buddy_opens_cannon_copy},
    { "macro_water_bomb_cannon" , macro_water_bomb_cannon},
    { "macro_bobomb_still" , macro_bobomb_still},
    { "macro_empty_116" , macro_empty_116},
    { "macro_empty_117" , macro_empty_117},
    { "macro_empty_118" , macro_empty_118},
    { "macro_empty_119" , macro_empty_119},
    { "macro_empty_120" , macro_empty_120},
    { "macro_empty_121" , macro_empty_121},
    { "macro_empty_122" , macro_empty_122},
    { "macro_unknown_123" , macro_unknown_123},
    { "macro_empty_124" , macro_empty_124},
    { "macro_unagi" , macro_unagi},
    { "macro_sushi" , macro_sushi},
    { "macro_empty_127" , macro_empty_127},
    { "macro_empty_128" , macro_empty_128},
    { "macro_empty_129" , macro_empty_129},
    { "macro_empty_130" , macro_empty_130},
    { "macro_empty_131" , macro_empty_131},
    { "macro_empty_132" , macro_empty_132},
    { "macro_empty_133" , macro_empty_133},
    { "macro_empty_134" , macro_empty_134},
    { "macro_empty_135" , macro_empty_135},
    { "macro_empty_136" , macro_empty_136},
    { "macro_unknown_137" , macro_unknown_137},
    { "macro_tornado" , macro_tornado},
    { "macro_pokey" , macro_pokey},
    { "macro_pokey_copy" , macro_pokey_copy},
    { "macro_tox_box" , macro_tox_box},
    { "macro_empty_142" , macro_empty_142},
    { "macro_empty_143" , macro_empty_143},
    { "macro_empty_144" , macro_empty_144},
    { "macro_empty_145" , macro_empty_145},
    { "macro_empty_146" , macro_empty_146},
    { "macro_empty_147" , macro_empty_147},
    { "macro_empty_148" , macro_empty_148},
    { "macro_empty_149" , macro_empty_149},
    { "macro_empty_150" , macro_empty_150},
    { "macro_monty_mole_2" , macro_monty_mole_2},
    { "macro_monty_mole" , macro_monty_mole},
    { "macro_monty_mole_hole" , macro_monty_mole_hole},
    { "macro_fly_guy" , macro_fly_guy},
    { "macro_empty_155" , macro_empty_155},
    { "macro_wiggler" , macro_wiggler},
    { "macro_empty_157" , macro_empty_157},
    { "macro_empty_158" , macro_empty_158},
    { "macro_empty_159" , macro_empty_159},
    { "macro_empty_160" , macro_empty_160},
    { "macro_empty_161" , macro_empty_161},
    { "macro_empty_162" , macro_empty_162},
    { "macro_empty_163" , macro_empty_163},
    { "macro_empty_164" , macro_empty_164},
    { "macro_spindrift" , macro_spindrift},
    { "macro_mr_blizzard" , macro_mr_blizzard},
    { "macro_mr_blizzard_copy" , macro_mr_blizzard_copy},
    { "macro_empty_168" , macro_empty_168},
    { "macro_small_penguin" , macro_small_penguin},
    { "macro_tuxies_mother" , macro_tuxies_mother},
    { "macro_tuxies_mother_copy" , macro_tuxies_mother_copy},
    { "macro_mr_blizzard_2" , macro_mr_blizzard_2},
    { "macro_empty_173" , macro_empty_173},
    { "macro_empty_174" , macro_empty_174},
    { "macro_empty_175" , macro_empty_175},
    { "macro_empty_176" , macro_empty_176},
    { "macro_empty_177" , macro_empty_177},
    { "macro_empty_178" , macro_empty_178},
    { "macro_empty_179" , macro_empty_179},
    { "macro_empty_180" , macro_empty_180},
    { "macro_empty_181" , macro_empty_181},
    { "macro_empty_182" , macro_empty_182},
    { "macro_empty_183" , macro_empty_183},
    { "macro_empty_184" , macro_empty_184},
    { "macro_empty_185" , macro_empty_185},
    { "macro_empty_186" , macro_empty_186},
    { "macro_empty_187" , macro_empty_187},
    { "macro_empty_188" , macro_empty_188},
    { "macro_haunted_chair_copy" , macro_haunted_chair_copy},
    { "macro_haunted_chair" , macro_haunted_chair},
    { "macro_haunted_chair_copy2" , macro_haunted_chair_copy2},
    { "macro_boo" , macro_boo},
    { "macro_boo_copy" , macro_boo_copy},
    { "macro_boo_group" , macro_boo_group},
    { "macro_boo_with_cage" , macro_boo_with_cage},
    { "macro_beta_key" , macro_beta_key},
    { "macro_empty_197" , macro_empty_197},
    { "macro_empty_198" , macro_empty_198},
    { "macro_empty_199" , macro_empty_199},
    { "macro_empty_200" , macro_empty_200},
    { "macro_empty_201" , macro_empty_201},
    { "macro_empty_202" , macro_empty_202},
    { "macro_empty_203" , macro_empty_203},
    { "macro_empty_204" , macro_empty_204},
    { "macro_empty_205" , macro_empty_205},
    { "macro_empty_206" , macro_empty_206},
    { "macro_empty_207" , macro_empty_207},
    { "macro_empty_208" , macro_empty_208},
    { "macro_empty_209" , macro_empty_209},
    { "macro_empty_210" , macro_empty_210},
    { "macro_empty_211" , macro_empty_211},
    { "macro_empty_212" , macro_empty_212},
    { "macro_empty_213" , macro_empty_213},
    { "macro_empty_214" , macro_empty_214},
    { "macro_empty_215" , macro_empty_215},
    { "macro_empty_216" , macro_empty_216},
    { "macro_empty_217" , macro_empty_217},
    { "macro_empty_218" , macro_empty_218},
    { "macro_empty_219" , macro_empty_219},
    { "macro_empty_220" , macro_empty_220},
    { "macro_empty_221" , macro_empty_221},
    { "macro_empty_222" , macro_empty_222},
    { "macro_empty_223" , macro_empty_223},
    { "macro_empty_224" , macro_empty_224},
    { "macro_empty_225" , macro_empty_225},
    { "macro_empty_226" , macro_empty_226},
    { "macro_empty_227" , macro_empty_227},
    { "macro_empty_228" , macro_empty_228},
    { "macro_empty_229" , macro_empty_229},
    { "macro_empty_230" , macro_empty_230},
    { "macro_empty_231" , macro_empty_231},
    { "macro_empty_232" , macro_empty_232},
    { "macro_empty_233" , macro_empty_233},
    { "macro_chirp_chirp" , macro_chirp_chirp},
    { "macro_seaweed_bundle" , macro_seaweed_bundle},
    { "macro_beta_chest" , macro_beta_chest},
    { "macro_water_mine" , macro_water_mine},
    { "macro_fish_group_4" , macro_fish_group_4},
    { "macro_fish_group_2" , macro_fish_group_2},
    { "macro_jet_stream_ring_spawner" , macro_jet_stream_ring_spawner},
    { "macro_jet_stream_ring_spawner_copy" , macro_jet_stream_ring_spawner_copy},
    { "macro_skeeter" , macro_skeeter},
    { "macro_clam_shell" , macro_clam_shell},
    { "macro_empty_244" , macro_empty_244},
    { "macro_empty_245" , macro_empty_245},
    { "macro_empty_246" , macro_empty_246},
    { "macro_empty_247" , macro_empty_247},
    { "macro_empty_248" , macro_empty_248},
    { "macro_empty_249" , macro_empty_249},
    { "macro_empty_250" , macro_empty_250},
    { "macro_ukiki" , macro_ukiki},
    { "macro_ukiki_2" , macro_ukiki_2},
    { "macro_piranha_plant" , macro_piranha_plant},
    { "macro_empty_254" , macro_empty_254},
    { "macro_whomp" , macro_whomp},
    { "macro_chain_chomp" , macro_chain_chomp},
    { "macro_empty_257" , macro_empty_257},
    { "macro_koopa" , macro_koopa},
    { "macro_koopa_shellless" , macro_koopa_shellless},
    { "macro_wooden_post_copy" , macro_wooden_post_copy},
    { "macro_fire_piranha_plant" , macro_fire_piranha_plant},
    { "macro_fire_piranha_plant_2" , macro_fire_piranha_plant_2},
    { "macro_thi_koopa_the_quick" , macro_thi_koopa_the_quick},
    { "macro_empty_264" , macro_empty_264},
    { "macro_empty_265" , macro_empty_265},
    { "macro_empty_266" , macro_empty_266},
    { "macro_empty_267" , macro_empty_267},
    { "macro_empty_268" , macro_empty_268},
    { "macro_empty_269" , macro_empty_269},
    { "macro_empty_270" , macro_empty_270},
    { "macro_empty_271" , macro_empty_271},
    { "macro_empty_272" , macro_empty_272},
    { "macro_empty_273" , macro_empty_273},
    { "macro_empty_274" , macro_empty_274},
    { "macro_empty_275" , macro_empty_275},
    { "macro_empty_276" , macro_empty_276},
    { "macro_empty_277" , macro_empty_277},
    { "macro_empty_278" , macro_empty_278},
    { "macro_empty_279" , macro_empty_279},
    { "macro_empty_280" , macro_empty_280},
    { "macro_moneybag" , macro_moneybag},
    { "macro_empty_282" , macro_empty_282},
    { "macro_empty_283" , macro_empty_283},
    { "macro_empty_284" , macro_empty_284},
    { "macro_empty_285" , macro_empty_285},
    { "macro_empty_286" , macro_empty_286},
    { "macro_empty_287" , macro_empty_287},
    { "macro_empty_288" , macro_empty_288},
    { "macro_swoop" , macro_swoop},
    { "macro_swoop_2" , macro_swoop_2},
    { "macro_mr_i" , macro_mr_i},
    { "macro_scuttlebug_spawner" , macro_scuttlebug_spawner},
    { "macro_scuttlebug" , macro_scuttlebug},
    { "macro_empty_294" , macro_empty_294},
    { "macro_empty_295" , macro_empty_295},
    { "macro_empty_296" , macro_empty_296},
    { "macro_empty_297" , macro_empty_297},
    { "macro_empty_298" , macro_empty_298},
    { "macro_empty_299" , macro_empty_299},
    { "macro_empty_300" , macro_empty_300},
    { "macro_empty_301" , macro_empty_301},
    { "macro_empty_302" , macro_empty_302},
    { "macro_unknown_303" , macro_unknown_303},
    { "macro_empty_304" , macro_empty_304},
    { "macro_empty_305" , macro_empty_305},
    { "macro_empty_306" , macro_empty_306},
    { "macro_empty_307" , macro_empty_307},
    { "macro_empty_308" , macro_empty_308},
    { "macro_empty_309" , macro_empty_309},
    { "macro_empty_310" , macro_empty_310},
    { "macro_empty_311" , macro_empty_311},
    { "macro_empty_312" , macro_empty_312},
    { "macro_ttc_rotating_cube" , macro_ttc_rotating_cube},
    { "macro_ttc_rotating_prism" , macro_ttc_rotating_prism},
    { "macro_ttc_pendulum" , macro_ttc_pendulum},
    { "macro_ttc_large_treadmill" , macro_ttc_large_treadmill},
    { "macro_ttc_small_treadmill" , macro_ttc_small_treadmill},
    { "macro_ttc_push_block" , macro_ttc_push_block},
    { "macro_ttc_rotating_hexagon" , macro_ttc_rotating_hexagon},
    { "macro_ttc_rotating_triangle" , macro_ttc_rotating_triangle},
    { "macro_ttc_pit_block" , macro_ttc_pit_block},
    { "macro_ttc_pit_block_2" , macro_ttc_pit_block_2},
    { "macro_ttc_elevator_platform" , macro_ttc_elevator_platform},
    { "macro_ttc_clock_hand" , macro_ttc_clock_hand},
    { "macro_ttc_spinner" , macro_ttc_spinner},
    { "macro_ttc_small_gear" , macro_ttc_small_gear},
    { "macro_ttc_large_gear" , macro_ttc_large_gear},
    { "macro_ttc_large_treadmill_2" , macro_ttc_large_treadmill_2},
    { "macro_ttc_small_treadmill_2" , macro_ttc_small_treadmill_2},
    { "macro_empty_330" , macro_empty_330},
    { "macro_empty_331" , macro_empty_331},
    { "macro_empty_332" , macro_empty_332},
    { "macro_empty_333" , macro_empty_333},
    { "macro_empty_334" , macro_empty_334},
    { "macro_empty_335" , macro_empty_335},
    { "macro_empty_336" , macro_empty_336},
    { "macro_empty_337" , macro_empty_337},
    { "macro_empty_338" , macro_empty_338},
    { "macro_box_star_2" , macro_box_star_2},
    { "macro_box_star_3",  macro_box_star_3},
    { "macro_box_star_4" , macro_box_star_4},
    { "macro_box_star_5" , macro_box_star_5},
    { "macro_box_star_6" , macro_box_star_6},
    { "macro_empty_344" , macro_empty_344},
    { "macro_empty_345" , macro_empty_345},
    { "macro_empty_346" , macro_empty_346},
    { "macro_empty_347" , macro_empty_347},
    { "macro_empty_348" , macro_empty_348},
    { "macro_empty_349" , macro_empty_349},
    { "macro_bits_sliding_platform" , macro_bits_sliding_platform},
    { "macro_bits_twin_sliding_platforms" , macro_bits_twin_sliding_platforms},
    { "macro_bits_unknown_352" , macro_bits_unknown_352},
    { "macro_bits_octagonal_platform" , macro_bits_octagonal_platform},
    { "macro_bits_staircase" , macro_bits_staircase},
    { "macro_empty_355" , macro_empty_355},
    { "macro_empty_356" , macro_empty_356},
    { "macro_bits_ferris_wheel_axle" , macro_bits_ferris_wheel_axle},
    { "macro_bits_arrow_platform" , macro_bits_arrow_platform},
    { "macro_bits_seesaw_platform" , macro_bits_seesaw_platform},
    { "macro_bits_tilting_w_platform" , macro_bits_tilting_w_platform},
    { "macro_empty_361" , macro_empty_361},
    { "macro_empty_362" , macro_empty_362},
    { "macro_empty_363" , macro_empty_363},
    { "macro_empty_364" , macro_empty_364},
    { "macro_empty_365" , macro_empty_365},
};



int main(){
      string in;
      while(getline(cin, in))
      {
            stringstream line(in);
            // grab up to (
            // if macro is first", "remove
            bool has_acts = false;
            bool has_beh = false;
            
            line >> in;

            int pos = in.find_first_of('(');
            string prefix = in.substr(0, in.find_first_of('('));
            in = in.substr(pos + 1);
            if (prefix == "MACRO_OBJECT") {
                prefix = "OBJECT";
            } else if (prefix == "MACRO_OBJECT_WITH_BEH_PARAM") {
                prefix = "OBJECT";
                has_beh = true;
            } else if (prefix == "MACRO_WITH_ACTS") {
                has_acts = true;
                prefix = "OBJECT_WITH_ACTS";
            } else if (prefix == "MACRO_OBJECT_WITH_BEH_PARAM_AND_ACTS") {
                prefix = "OBJECT_WITH_ACTS";
                has_acts = true;
                has_beh = true;
            } else {
                continue;
            }

            // Assumes standered way of parsing stuff

            line >> in;
            if ( in[in.length() -1] == ',') {
                in = in.substr(0, in.length() - 1);
            }

            MacroPresets check = macroNameMap[in];

            int yaw, x, y, z;
            string beh = "";
            line >> in >> yaw >> in >> in >> x >> in >> y >> in >> z >> in;
            if ( has_beh) {
                string temp;
                line >> in >> beh;
                if (beh.substr(beh.length() -2) == "),"){
                    beh.erase(beh .length()-2);
                }
            }

            // a mess
            string beh_print = macroStrings[check][2];
            if (beh_print != "0") {
                beh_print = "(" + beh_print +" &0x00FF)";
                beh_print = (has_beh ? "(" + beh + " & 0xFF00) + " : "") + beh_print; 
            } else if ( has_beh){
                beh_print = beh;
            }

            beh_print = "(" + beh_print + " << 16) + (" + beh_print + " & 0xFF00)";
        

            cout << prefix << "(/*model*/ " << macroStrings[check][1] << ", /*pos*/ "<< setw(5) << x << ',' << setw(6) << y
            << ',' << setw(6) << z << ", /*angle*/     0, " << setw(5) << yaw << ",     0, /*behParam*/ "
            << beh_print << ", /*beh*/ " << macroStrings[check][0] << ")," << endl;


      }
      return 0;
}
